### ISSUE TITLE
conferenceengineer.com is down.

### ISSUE THREAD

**Issue by tasomaniac** [FunkyAndroid/iosched#45]
Is it temporary or is it closed completely? 

It was super easy to use this system. I am about to make the application for [Women Techmakers Istanbul 2015](http://wtmistanbul.com) and I have to decide what to do.

**Comment by tasomaniac** [comment]
Are you going to make the backend code for conferenceengineer.com open source as well? Please do. @alsutton @kevinmcdonagh

**Comment by alsutton** [comment]
The server side has been open sourced at https://github.com/novoda/iosched-webapp
